# Generated by Django 3.0.10 on 2021-03-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='households',
            fields=[
                ('Hshd_num', models.TextField(primary_key=True, serialize=False)),
                ('Loyalty_flag', models.TextField()),
                ('Age_range', models.TextField()),
                ('Marital_status', models.TextField()),
                ('Income_range', models.TextField()),
                ('Homeowner_desc', models.TextField()),
                ('Hshd_composition', models.TextField()),
                ('Hshd_size', models.TextField()),
                ('Children', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('Product_num', models.IntegerField(primary_key=True, serialize=False)),
                ('Department', models.TextField()),
                ('Commodity', models.TextField()),
                ('Brand_type', models.TextField()),
                ('natural_Organic_Flag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basket_num', models.IntegerField()),
                ('Date', models.DateField()),
                ('Spend', models.FloatField()),
                ('Units', models.IntegerField()),
                ('Store_region', models.TextField()),
                ('Week_num', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Hshd_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.households', verbose_name='hshd_id')),
                ('Product_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.products', verbose_name='product_id')),
            ],
        ),
    ]
